### ISSUE TITLE
Future Update Idea

### ISSUE THREAD

**Issue by jm6087** [TheCre8r/WME-Road-Shield-Helper#27]
Convert the following arrays to Google Sheets so that updates can be made w/o script changes

        let SHStates = ['Colorado', 'Minnesota', 'Oklahoma', 'Texas'];
        let SRStates = ['Alabama', 'Arizona', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Illinois', 'Massachusetts', 'New Hampshire', 'New Jersey', 'New Mexico', 'Ohio', 'Pennsylvania', 'Utah', 'Washington'];
        let CRStates = ['Alabama', 'Arkansas', 'Florida', 'Louisiana', 'New Jersey', 'New York'];

**Comment by TheCre8r** [comment]
I think due to the nature of how the script works, I would rather require it per state rather than a sheet for all of the states. It allows verification rather than just assuming it works correctly for every use case in the corresponding state. I think at least for now, I don't plan on expanding to use Google Sheets. Great idea, though!
